import ChatMessage from "../models/ChatMessage.js";
import ChatEnquiry from "../models/ChatEnquiry.js";
import { room } from "../config/socket.js";
import { notifyNewLead, notifyHandoffStarted, notifyFlowComplete } from "./chatSlackNotifier.js";

/**
 * Anonymous Chat / lead-gen chatbot — the state machine (equivalent to
 * V1's services/interactiveChatService.js handleInteractiveMessage). Ported
 * step-for-step per the client's own spec (question text, option
 * labels/values, and the exact status transitions), adapted to this
 * codebase's models/conventions and with the FCM/EM-notification and
 * Slack-Lists-ticketing pieces removed — see info.txt for why (checked
 * with the user first: no EventManager/device-token system exists in this
 * backend, and V1's Slack integration is hardcoded to a workspace
 * configuration this project doesn't have).
 *
 * Called once per inbound user message from customerChatController.js's
 * sendMessage. Every reply is generated by looking at the CURRENT
 * ChatEnquiry.status and deciding what to ask next — the same pattern the
 * client's own spec names step-by-step in its "Next Steps for Interns"
 * section (add a new status + a new `if` block to extend the flow).
 */

async function sendBotMessage(chatId, io, content, messageType = "text", options = null, delayMs = 50) {
  return new Promise((resolve) => {
    setTimeout(async () => {
      try {
        const msg = await ChatMessage.create({
          chatId,
          sender: "bot",
          senderId: "bot",
          messageType,
          messageContent: content,
          options,
        });
        if (io) io.to(room(chatId)).emit("new_message", msg.toObject());
        resolve(msg);
      } catch (err) {
        console.error("[chatBotEngine] Failed to send bot message:", err);
        resolve(null);
      }
    }, delayMs);
  });
}

// Services that imply we still need a headcount before budget.
const needsGuestCount = (services) =>
  (services || []).some((s) => {
    const ls = s.toLowerCase();
    return ls.includes("catering") || ls.includes("venue");
  });

const SERVICE_OPTIONS = [
  { label: "Catering", value: "Catering" },
  { label: "Venue", value: "Venue" },
  { label: "Photography / Videography", value: "Photography / Videography" },
  { label: "Decoration & Florals", value: "Decoration & Florals" },
  { label: "Music / Entertainment", value: "Music / Entertainment" },
  { label: "Makeup & Styling", value: "Makeup & Styling" },
  { label: "Others", value: "Others" },
];

const GUEST_COUNT_OPTIONS = [
  { label: "Under 25", value: "Under 25" },
  { label: "25–50", value: "25–50" },
  { label: "50–100", value: "50–100" },
  { label: "100–200", value: "100–200" },
  { label: "200+", value: "200+" },
  { label: "Not sure yet", value: "Not sure yet" },
];

const BUDGET_OPTION_CHOICES = [
  { label: "Yes, I have a rough number", value: "BUDGET_YES" },
  { label: "Not decided yet", value: "BUDGET_NO" },
];

async function askGuestCountOrBudget(enquiry, chatId, io) {
  if (needsGuestCount(enquiry.servicesNeeded)) {
    enquiry.status = "COLLECTING_GUEST_COUNT";
    await enquiry.save();
    await sendBotMessage(chatId, io, "Around how many guests are you expecting?", "options", GUEST_COUNT_OPTIONS);
  } else {
    enquiry.status = "COLLECTING_BUDGET_OPTION";
    await enquiry.save();
    await sendBotMessage(chatId, io, "Almost there! Do you have a budget in mind for this event?", "options", BUDGET_OPTION_CHOICES);
  }
}

async function handleStep8Handoff(enquiry, chatId, io) {
  enquiry.status = "COLLECTING_NAME";
  await enquiry.save();

  notifyHandoffStarted(enquiry).catch((err) => console.error("[chatBotEngine] notifyHandoffStarted failed:", err));

  await sendBotMessage(chatId, io, "This already sounds exciting! Here's how we'll help you:", "text", null, 50);
  const mgrText =
    "A dedicated Event Manager (FREE) will:\n" +
    "• Share curated options\n" +
    "• Suggest themes & ideas\n" +
    "• Help you plan within your budget\n" +
    "• Handle the entire coordination\n\n" +
    "So you can enjoy the event stress-free! To make sure they can reach you quickly, could you share a couple of details?";
  await sendBotMessage(chatId, io, mgrText, "text", null, 1000);
  await sendBotMessage(chatId, io, "Your name? (First name works just fine!)", "text", null, 1000);
}

/**
 * @desc Advances a ChatEnquiry's state machine by one turn based on the
 * user's latest message, and sends whatever bot reply/replies follow.
 * @param {string} chatId
 * @param {{anonId?: string, customerId?: string}} identity - exactly one set
 * @param {string} messageContent
 * @param {import("socket.io").Server} io
 */
export async function handleBotTurn(chatId, identity, messageContent, io) {
  try {
    const isAnon = Boolean(identity.anonId);
    const enquiryFilter = isAnon
      ? { anonId: identity.anonId, status: { $nin: ["CLOSED", "CONVERTED"] } }
      : { customerId: identity.customerId, status: { $nin: ["CLOSED", "CONVERTED"] } };

    let enquiry = await ChatEnquiry.findOne(enquiryFilter).sort({ createdAt: -1 });

    const normalizedContent = (messageContent || "").toString().trim();
    const lowerContent = normalizedContent.toLowerCase();

    const eventKeywords = [
      "birthday", "anniversary", "wedding", "annaprashan", "baby shower",
      "housewarming", "social", "corporate", "party", "gathering",
      "celebration", "event", "else",
    ];
    const isKnownEventType = !normalizedContent.startsWith("[") && eventKeywords.some((k) => lowerContent.includes(k));

    // No active enquiry yet, or still OPEN, or this message looks like an
    // event-type answer — (re)start / advance from event-type capture.
    if (!enquiry || enquiry.status === "OPEN" || isKnownEventType) {
      if (enquiry) {
        enquiry.eventType = normalizedContent;
        enquiry.status = "COLLECTING_DATE";
        await enquiry.save();
      } else {
        enquiry = await ChatEnquiry.create({
          ...(isAnon ? { anonId: identity.anonId } : { customerId: identity.customerId }),
          eventType: normalizedContent,
          status: "COLLECTING_DATE",
        });
      }

      notifyNewLead(enquiry).catch((err) => console.error("[chatBotEngine] notifyNewLead failed:", err));

      await sendBotMessage(chatId, io, "Love it! Now, when are you planning to host it?", "date_picker", [
        { label: "Still exploring - not sure yet", value: "STILL_EXPLORING" },
      ]);
      return;
    }

    if (enquiry.status === "COLLECTING_DATE") {
      const parsedDate = parseEventDate(normalizedContent);
      enquiry.eventDate = parsedDate;
      enquiry.eventDateRaw = normalizedContent;
      enquiry.status = "COLLECTING_LOCATION";
      await enquiry.save();
      await sendBotMessage(chatId, io, "Got it! Which city or area is the event in?");
      return;
    }

    if (enquiry.status === "COLLECTING_LOCATION") {
      enquiry.city = normalizedContent;
      enquiry.status = "COLLECTING_VENUE_SETTING";
      await enquiry.save();
      await sendBotMessage(chatId, io, "Is this event happening at home or at an outside venue?", "options", [
        { label: "At home", value: "At home" },
        { label: "Outdoor / Outside venue", value: "Outdoor / Outside venue" },
      ]);
      return;
    }

    if (enquiry.status === "COLLECTING_VENUE_SETTING") {
      enquiry.venueSetting = normalizedContent;

      if (lowerContent.includes("outside") || lowerContent.includes("outdoor")) {
        enquiry.status = "COLLECTING_VENUE_DECISION";
        await enquiry.save();
        await sendBotMessage(
          chatId,
          io,
          "Have you already decided on a venue, or would you like Eventory to help find one?",
          "options",
          [
            { label: "Yes, I have a venue in mind", value: "VENUE_YES" },
            { label: "I need help finding a venue", value: "VENUE_HELP" },
          ]
        );
      } else {
        enquiry.status = "COLLECTING_SERVICES";
        await enquiry.save();
        await sendBotMessage(chatId, io, "Perfect! What kind of services are you looking for? (Select all that apply)", "multi_select", SERVICE_OPTIONS);
      }
      return;
    }

    if (enquiry.status === "COLLECTING_VENUE_DECISION") {
      enquiry.venueHelpNeeded = lowerContent.includes("help");
      enquiry.status = "COLLECTING_SERVICES";
      await enquiry.save();
      await sendBotMessage(chatId, io, "Perfect! What kind of services are you looking for? (Select all that apply)", "multi_select", SERVICE_OPTIONS);
      return;
    }

    if (enquiry.status === "COLLECTING_SERVICES") {
      let services = [];
      if (normalizedContent.startsWith("[") && normalizedContent.endsWith("]")) {
        try {
          services = JSON.parse(normalizedContent);
        } catch {
          services = [normalizedContent];
        }
      } else {
        services = [normalizedContent];
      }
      enquiry.servicesNeeded = services;

      const hasOthers = services.some((s) => s.toLowerCase().includes("others"));
      if (hasOthers) {
        enquiry.status = "COLLECTING_OTHER_SERVICES_DETAILS";
        enquiry.pendingOthersInput = true;
        await enquiry.save();
        await sendBotMessage(chatId, io, "Could you tell us more about the other services you need?");
        return;
      }

      await askGuestCountOrBudget(enquiry, chatId, io);
      return;
    }

    if (enquiry.status === "COLLECTING_OTHER_SERVICES_DETAILS") {
      enquiry.otherServiceDetails = normalizedContent;
      enquiry.pendingOthersInput = false;
      await enquiry.save();
      await askGuestCountOrBudget(enquiry, chatId, io);
      return;
    }

    if (enquiry.status === "COLLECTING_GUEST_COUNT") {
      enquiry.guestCount = normalizedContent;
      enquiry.status = "COLLECTING_BUDGET_OPTION";
      await enquiry.save();
      await sendBotMessage(chatId, io, "Almost there! Do you have a budget in mind for this event?", "options", BUDGET_OPTION_CHOICES);
      return;
    }

    if (enquiry.status === "COLLECTING_BUDGET_OPTION") {
      const hasBudget = lowerContent.includes("yes");
      enquiry.budgetOption = hasBudget ? "Yes" : "No";

      if (hasBudget) {
        enquiry.status = "COLLECTING_BUDGET_RANGE";
        await enquiry.save();
        await sendBotMessage(chatId, io, "What's your approximate budget range?", "options", [
          { label: "Under ₹20,000", value: "Under ₹20,000" },
          { label: "₹20,000 – ₹60,000", value: "₹20,000 – ₹60,000" },
          { label: "₹60,000 – ₹1,00,000", value: "₹60,000 – ₹1,00,000" },
          { label: "Above ₹1,00,000", value: "Above ₹1,00,000" },
          { label: "Prefer to discuss with the manager", value: "Prefer to discuss with the manager" },
        ]);
      } else {
        await handleStep8Handoff(enquiry, chatId, io);
      }
      return;
    }

    if (enquiry.status === "COLLECTING_BUDGET_RANGE") {
      enquiry.budgetRange = normalizedContent;
      await enquiry.save();
      await handleStep8Handoff(enquiry, chatId, io);
      return;
    }

    if (enquiry.status === "COLLECTING_NAME") {
      enquiry.customerName = normalizedContent;
      enquiry.status = "COLLECTING_PHONE";
      await enquiry.save();
      await sendBotMessage(chatId, io, "Your phone number?");
      return;
    }

    if (enquiry.status === "COLLECTING_PHONE") {
      const digitsOnly = normalizedContent.replace(/\D/g, "");
      if (digitsOnly.length !== 10 || /^[0-5]/.test(digitsOnly)) {
        await sendBotMessage(chatId, io, "Please enter a valid 10-digit Indian mobile number (starting with 6, 7, 8, or 9).");
        return;
      }
      enquiry.phoneNumber = digitsOnly;
      enquiry.status = "COLLECTING_CALL_TIME";
      await enquiry.save();
      await sendBotMessage(chatId, io, "Best time to call? (Optional but helpful)", "options", [
        { label: "Morning (9am–12pm)", value: "Morning (9am–12pm)" },
        { label: "Afternoon (12pm–4pm)", value: "Afternoon (12pm–4pm)" },
        { label: "Evening (4pm–8pm)", value: "Evening (4pm–8pm)" },
        { label: "Anytime works!", value: "Anytime works!" },
      ]);
      return;
    }

    if (enquiry.status === "COLLECTING_CALL_TIME") {
      enquiry.bestTimeToCall = normalizedContent;
      enquiry.status = "FLOW_COMPLETE";
      await enquiry.save();

      const name = enquiry.customerName || "there";
      const phone = enquiry.phoneNumber || "the provided number";

      await sendBotMessage(chatId, io, `Wonderful, ${name}! Your event brief is with us. One of our Event Managers will call you shortly at ${phone}.`, "text");
      await sendBotMessage(
        chatId,
        io,
        "Thanks for sharing! Feel free to share more about your event plans and ideas. Our team will review and suggest personalised options.",
        "flow_complete"
      );

      notifyFlowComplete(enquiry).catch((err) => console.error("[chatBotEngine] notifyFlowComplete failed:", err));
      return;
    }
  } catch (error) {
    console.error("[chatBotEngine] CRITICAL ERROR in handleBotTurn:", error);
  }
}

// Robust date parser for freeform user input — ported as-is from V1's
// interactiveChatService.js (well-tested pattern coverage: ISO, DD/MM/YYYY,
// "21sep", "September 21", etc.), no behavior changes.
function parseEventDate(input) {
  if (!input || typeof input !== "string") return null;
  const raw = input.trim();
  const currentYear = new Date().getFullYear();

  const MONTH_MAP = {
    jan: 0, january: 0, feb: 1, february: 1, mar: 2, march: 2, apr: 3, april: 3,
    may: 4, jun: 5, june: 5, jul: 6, july: 6, aug: 7, august: 7,
    sep: 8, sept: 8, september: 8, oct: 9, october: 9, nov: 10, november: 10, dec: 11, december: 11,
  };

  const makeDate = (year, monthIndex, day) => {
    if (monthIndex < 0 || monthIndex > 11 || day < 1 || day > 31 || year < 2020 || year > 2100) return null;
    const d = new Date(Date.UTC(year, monthIndex, day));
    if (d.getUTCMonth() !== monthIndex || d.getUTCDate() !== day) return null;
    return d;
  };

  {
    const m = raw.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);
    if (m) return makeDate(+m[1], +m[2] - 1, +m[3]);
  }
  {
    const m = raw.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})$/);
    if (m) {
      const year = +m[3] < 100 ? 2000 + +m[3] : +m[3];
      return makeDate(year, +m[2] - 1, +m[1]);
    }
  }
  {
    const m = raw.match(/^(\d{1,2})[\/\-.](\d{1,2})$/);
    if (m) return makeDate(currentYear, +m[2] - 1, +m[1]);
  }
  {
    const m = raw
      .toLowerCase()
      .match(/^(\d{1,2})(st|nd|rd|th)?\s*(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)(\s*(\d{2,4}))?$/);
    if (m) {
      const day = +m[1];
      const monthKey = m[3].replace(/[^a-z]/g, "");
      const monthIdx = MONTH_MAP[monthKey] ?? MONTH_MAP[monthKey.slice(0, 3)] ?? null;
      if (monthIdx == null) return null;
      let year = currentYear;
      if (m[5]) year = +m[5] < 100 ? 2000 + +m[5] : +m[5];
      return makeDate(year, monthIdx, day);
    }
  }
  {
    const m = raw
      .toLowerCase()
      .match(/^(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)\s+(\d{1,2})(st|nd|rd|th)?[\s,]*(\d{2,4})?$/);
    if (m) {
      const monthKey = m[1].replace(/[^a-z]/g, "");
      const monthIdx = MONTH_MAP[monthKey] ?? MONTH_MAP[monthKey.slice(0, 3)] ?? null;
      if (monthIdx == null) return null;
      const day = +m[2];
      let year = currentYear;
      if (m[4]) year = +m[4] < 100 ? 2000 + +m[4] : +m[4];
      return makeDate(year, monthIdx, day);
    }
  }
  {
    const m = raw
      .toLowerCase()
      .match(/^(\d{1,2})(st|nd|rd|th)?\s+(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)[\s,]*(\d{2,4})?$/);
    if (m) {
      const day = +m[1];
      const monthKey = m[3].replace(/[^a-z]/g, "");
      const monthIdx = MONTH_MAP[monthKey] ?? MONTH_MAP[monthKey.slice(0, 3)] ?? null;
      if (monthIdx == null) return null;
      let year = currentYear;
      if (m[4]) year = +m[4] < 100 ? 2000 + +m[4] : +m[4];
      return makeDate(year, monthIdx, day);
    }
  }
  {
    const m = raw.match(/^(\d{4})(\d{2})(\d{2})$/);
    if (m) return makeDate(+m[1], +m[2] - 1, +m[3]);
  }

  console.warn(`[chatBotEngine] Could not parse date from input: "${raw}"`);
  return null;
}

export default { handleBotTurn };
